### ISSUE TITLE
kwic window size

### ISSUE THREAD

**Issue by akv17** [lingcorpora/lingcorpora.py#11]
Сейчас имеются параметры `nLeft` и `nRight`, насколько я понял, отвечающие за кол-во слов слева / справа в kwic выдаче. НКРЯ не позволяет задавать различное число слов слева / справа и требует одно значение *k*, выдавая *k* слов слева и *k* слов справа. Соответственно, для корпусов, которые так устроены, требуется следить за этим. Как это лучше сделать?
Возможные идеи:
- если `nRight` и `nLeft` не совпадают, поднимать исключение вида `"nRight must be equal to nLeft"` для корпусов типа НКРЯ (не очень)
- перейти на один `tuple` аргумент вроде `kwic_size`, который может быть длины 1 или 2 и следить за его длиной в ф-ии соответствующего корпуса (или, наверное, прямо в `oop_template` можно следить в зависимости от параметра `language`)

**Comment by akv17** [comment]
UPD: для НКРЯ вопрос снят, ничего менять не нужно.
Если для других корпусов этот вопрос не актуален, можно закрывать issue

**Comment by agricolamz** [comment]
Стоп,  мы сами не можем что-ли посчитать слова?

**Comment by akv17** [comment]
@agricolamz этот вопрос более не актуален, закрываю
