### ISSUE TITLE
прогрессбар или вербозность <- корпуса как генераторы

### ISSUE THREAD

**Issue by kategaranina** [lingcorpora/lingcorpora.py#13]
прогрессбар - вербозность
сделать отдельные корпуса генератором?
избавиться от page parser, сделать через downloader генератор

**Comment by agricolamz** [comment]
Помогите... Не понятно...

**Comment by kategaranina** [comment]
@agricolamz это структурное внутреннее изменение, которое позволило прикрутить прогрессбар. Раньше внутри одного API собирался массив результатов и передавался наверх. Сейчас один API возвращает результаты построчно - то есть является генератором. И вот это построчная выдача результата позволяет продвигать прогрессбар.
