### ISSUE TITLE
Dictionary template

### ISSUE THREAD

**Issue by agricolamz** [lingcorpora/lingcorpora.py#16]
There are some dictionaries in our list, so I expect @Pandaklez working on template. How to apply everything that have been done to dictionaries?

**Comment by akv17** [comment]
Generally, @Pandaklez has to stream results as `Target` objects via `yield`.
I'll have some example templates (including yielding, `Target` and `Result` objects) done by the end of the week.
Still it might be good to have a look at @Pandaklez code and also its gonna be even better for us (at least me) at first to understand the basics of querying the dictionaries (like, what's the query like, what are the results and so on).

**Comment by agricolamz** [comment]
@Pandaklez, if you have problems with spreadthesign, just try to do something with macedonian dictionary. It is really simple and worth doing as a toy background to the final template.
