### ISSUE TITLE
Import crash, python 3.10 

### ISSUE THREAD

**Issue by fat-crocodile** [lingcorpora/lingcorpora.py#43]
There is a clause in the [what's new in python 3.10](https://docs.python.org/3/whatsnew/3.10.html)

Remove deprecated aliases to Collections Abstract Base Classes from the collections module. (Contributed by Victor Stinner in bpo-37324.)

It affects corpus.py here

`from collections import Iterable, deque
`

This line fails with an error 

ImportError: cannot import name 'Iterable' from 'collections' 

I suggest replacing the line with

```
from collections import deque
from collections.abc import Iterable
```

This variant works at least on both 3.10 and 3.9

**Comment by gisly** [comment]
Thank you! We've applied the changes you are suggesting.
